trigger:
- main

pool:
  name: Default

jobs:
- job: BuildAndDeploy
  displayName: Deploy FastAPI App

  steps:
  - checkout: self

  - script: |
        echo "Installing dependencies"

        # Clean virtual environment
        rm -rf venv

        python3 -m venv venv
        ./venv/bin/pip install -r requirements.txt
    displayName: Install Dependencies

  - script: |
        echo "Stopping old FastAPI server"
        pkill -f uvicorn || true
    displayName: Stop Old App

  - script: |
        echo "Starting FastAPI server"

        cd $(Build.SourcesDirectory)

        nohup ./venv/bin/uvicorn app:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
        disown
    displayName: Start FastAPI